Repository syncfusion-content/blazor-docs, pull requests merged in 2022-04, with the labels that each got.

#649 BLAZ-21427-BringIntoViewCenter
  blazor/diagram-component/commands.md
Labels: documentation

#602 BLAZ-21427-BringIntoViewCenter
  blazor/diagram-component/commands.md
Labels: documentation

#589 feature(BLAZ-21416): Clear method has been added in UG document
  blazor/diagram-component/images/Clear.gif
  blazor/diagram-component/methods.md
Labels: enhancement

#651 BLAZ-21428 FitPage UG
  blazor/diagram-component/commands.md
  blazor/diagram-component/images/FitToPage.gif
  blazor/diagram-component/images/Region.gif
Labels: enhancement

#654 BLAZ-21428 FitPage
  blazor/diagram-component/commands.md
  blazor/diagram-component/images/FitToPage.gif
  blazor/diagram-component/images/Region.gif
Labels: enhancement

#601 BLAZ-21429-TextNode
  blazor/diagram-component/images/blazor-diagram-Text-drawingtool.gif
  blazor/diagram-component/shapes.md
  blazor/diagram-component/tools.md
Labels: enhancement

#686 (EJ2-59206): Breadcrumb Documentation in Blazor
  blazor/breadcrumb/images/breadcrumb-collapsed.png
  blazor/breadcrumb/images/breadcrumb-hidden.png
  blazor/breadcrumb/images/breadcrumb-menu.png
  blazor/breadcrumb/images/breadcrumb-scroll.png
  blazor/breadcrumb/images/breadcrumb-specific-item-template.png
  blazor/breadcrumb/images/breadcrumb-wrap.png
  blazor/breadcrumb/overflow.md
  blazor/breadcrumb/templates.md
Labels: documentation

#673 BLAZ-21858-TextNode Output image added
  blazor/diagram-component/images/blazor-diagram-TextNode.png
  blazor/diagram-component/shapes.md
Labels: documentation

#672 BLAZ-21858-TextNode Output image added
  blazor/diagram-component/images/blazor-diagram-TextNode.png
  blazor/diagram-component/shapes.md
Labels: documentation

#708 (EJ2-59206): Breadcrumb Documentation in Blazor
  blazor/breadcrumb/images/bread-overflow-hidden.png
  blazor/breadcrumb/overflow.md
Labels: documentation

#707 documentation(BLAZ-21928): added customized styles UG for in-place editort and topic autofit columns while using column chooser.
  blazor/datagrid/columns.md
  blazor/in-place-editor/images/outer-style-like-material-filled.png
  blazor/in-place-editor/style.md
Labels: documentation

#733 documentation(BLAZ-19819): carousel UG review corrections addressed
  blazor-toc.html
  blazor/carousel/accessibility.md
  blazor/carousel/animations-and-transitions.md
  blazor/carousel/getting-started.md
  blazor/carousel/images/blazor-carousel-component.gif
  blazor/carousel/images/blazor-carousel-component.png
  blazor/carousel/navigators-and-indicators.md
  blazor/carousel/populating-items.md
Labels: documentation

#743 sample(BLAZ-19819): carousel review corrections addressed
  blazor-toc.html
  blazor/carousel/animations-and-transitions.md
  blazor/carousel/getting-started.md
  blazor/carousel/images/auto_play.png
  blazor/carousel/images/blazor-carousel-component.gif
  blazor/carousel/images/getting_started.png
  blazor/carousel/images/indicators.png
  blazor/carousel/images/indicators_preview.png
  blazor/carousel/images/indicators_template.png
  blazor/carousel/images/looping_slides.png
  blazor/carousel/images/navigators_hidden.png
  blazor/carousel/images/navigators_onhover.gif
  blazor/carousel/images/navigators_template.png
  blazor/carousel/images/play_button.png
  blazor/carousel/images/play_button_template.png
  blazor/carousel/navigators-and-indicators.md
  blazor/carousel/populating-items.md
Labels: bug, documentation
